// <auto-generated />
namespace PoliticImpact.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CaseItem2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CaseItem2));
        
        string IMigrationMetadata.Id
        {
            get { return "201211062124249_CaseItem2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
