// <auto-generated />
namespace PoliticImpact.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CaseItem5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CaseItem5));
        
        string IMigrationMetadata.Id
        {
            get { return "201211062159574_CaseItem5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
