// <auto-generated />
namespace PoliticImpact.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CaseItem4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CaseItem4));
        
        string IMigrationMetadata.Id
        {
            get { return "201211062150570_CaseItem4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
